%% Linear vs Quadratic fit LLR Comparison
neuron_filter = logical(ones(size(stats,1),1)); %stats.evoked_spikes<0.05;

figure; hold on;
%% pEvoked_v_pBase_LLR
subplot(1,4,1); hold on;
histogram(stats.pEvoked_v_pBase_LLR(logical(session_numbers_unique)),'BinWidth',1, 'FaceColor',[0 174 239]./255)
xline(3.841);
title({'pEvoked vs pBase LLR', ['NAN = ' num2str(sum(isnan(stats.pEvoked_v_pBase_LLR(logical(session_numbers_unique)))))]});
fprintf('Monkey Oz: %d/%d\n', ...
                    sum(stats.pEvoked_v_pBase_LLR > 3.841 & stats.monkey_id == 1 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 1 & logical(session_numbers_unique)'));
fprintf('Monkey Ci: %d/%d\n', ...
                    sum(stats.pEvoked_v_pBase_LLR > 3.841 & stats.monkey_id == 2 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 2 & logical(session_numbers_unique)'));
%% sEvoked_v_sBase_LLR
subplot(1,4,2); hold on;
histogram(stats.sEvoked_v_sBase_LLR(neuron_filter),'BinWidth',1, 'FaceColor','r')
xline(3.841);
title({'sEvoked vs sBase LLR', ['NAN = ' num2str(sum(isnan(stats.sEvoked_v_sBase_LLR(neuron_filter))))]});
fprintf('Monkey Oz: %d/%d\n', ...
                    sum(stats.sEvoked_v_sBase_LLR > 3.841 & stats.monkey_id == 1 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 1 & neuron_filter));
fprintf('Monkey Ci: %d/%d\n', ...
                    sum(stats.sEvoked_v_sBase_LLR > 3.841 & stats.monkey_id == 2 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 2 & neuron_filter));
%% pEvoked_v_sBase_LLR
subplot(1,4,3); hold on;
histogram(stats.pEvoked_v_sBase_LLR(neuron_filter),'BinWidth',1,'FaceColor',[0.5 0.5 0.5])
xline(3.841);
title({'pEvoked vs sBase LLR', ['NAN = ' num2str(sum(isnan(stats.pEvoked_v_sBase_LLR(neuron_filter))))]});
fprintf('Monkey Oz: %d/%d\n', ...
                    sum(stats.pEvoked_v_sBase_LLR > 3.841 & stats.monkey_id == 1 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 1 & neuron_filter));
fprintf('Monkey Ci: %d/%d\n', ...
                    sum(stats.pEvoked_v_sBase_LLR > 3.841 & stats.monkey_id == 2 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 2 & neuron_filter));
%% sEvoked_v_pBase_LLR
subplot(1,4,4); hold on;
histogram(stats.sEvoked_v_pBase_LLR(neuron_filter),'BinWidth',1,'FaceColor',[0.5 0.5 0.5])
xline(3.841);
title({'sEvoked vs pBase LLR', ['NAN = ' num2str(sum(isnan(stats.sEvoked_v_pBase_LLR(neuron_filter))))]});
fprintf('Monkey Oz: %d/%d\n', ...
                    sum(stats.sEvoked_v_pBase_LLR > 3.841 & stats.monkey_id == 1 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 1 & neuron_filter));
fprintf('Monkey Ci: %d/%d\n', ...
                    sum(stats.sEvoked_v_pBase_LLR > 3.841 & stats.monkey_id == 2 & logical(session_numbers_unique)'),...
                    sum(stats.monkey_id == 2 & neuron_filter));